import { Roboto } from "next/font/google";
import "./globals.css";

// Initialize Roboto with the weights you need
const roboto = Roboto({
  weight: ['300', '400', '500', '700'],  // you can choose the weights you need
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
});

function Loading() {
  return (
    <div className="flex justify-center items-center min-h-screen">
      <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-blue-500"></div>
    </div>
  );
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}