// app/layout.jsx
import { Roboto } from "next/font/google"
import "./globals.css"
import Header from "../layout/header"

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
})

function Loading() {
  return (
    <div className="flex justify-center items-center min-h-screen">
      <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-blue-500"></div>
    </div>
  )
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <div className="background min-h-screen">
          <div className="px-[20px] md:px-0 w-full pt-3">
            <Header />
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}